### ISSUE TITLE
SH2 fusion rules

### ISSUE THREAD

**Issue by LisandraBrave** [aqiu384/megaten-fusion-tool#118]
Unless it changes later in the game, inheritances for skills a demon has a weakness to are disallowed, and at present the calculator doesn't take that into account

**Comment by aqiu384** [comment]
Fixed with [82cf573](https://github.com/aqiu384/megaten-fusion-tool/commit/82cf57353535f125d19b5d6f32ef1f6d32f8c57e)

**Comment by Martyriel** [comment]
Hi, not sure why, but at present the calculator still doesn't take it into account. e.g. Rakshasa [Null Phys (46)] x Silky [Bufudyne] = Decarabia wont work, since Decarabia is weak to ice. Thanks for your work.
